sample(form): add sample and config - vNext
IgniteUI/igniteui-wc-examples pull request #108
Opened 2021-10-20 13:30 UTC by igdmdimitrov

Closes #102

2021-10-29 10:59 UTC, zhosti commented on samples/data/form/overview/index.html
> +    <link rel="stylesheet" href="./node_modules/igniteui-webcomponents/src/styles/themes/material.css" type="text/css"></link>
In order to load form styles in browser, add `import 'igniteui-webcomponents/src/styles/themes/material.css'` in `index.ts` file and remove it from `index.html`.

2021-11-02 09:47 UTC, zhosti approved these changes

2021-11-02 12:27 UTC, gedinakova commented
@igdmdimitrov The FormaData object is empty.

2021-11-02 12:30 UTC, gedinakova requested changes

2021-11-02 12:30 UTC, gedinakova commented on browser/src/router.ts
> +import { RouterData } from "./samples/data/router";
As per Martin's request we need to rename the data forlder to something else. He suggested "inputs".

2021-11-02 12:30 UTC, gedinakova commented on samples/data/form/overview/.prettierrc
> +{
As per Martin's request we need to rename the data forlder to something else. He suggested "inputs".

2021-11-02 17:14 UTC, HUSSAR-mtrela approved these changes

2021-11-02 17:17 UTC, HUSSAR-mtrela approved these changes

2021-11-02 17:18 UTC, merged