Updated import statements and theme.
IgniteUI/igniteui-wc-examples pull request #143
Opened 2021-11-08 15:02 UTC by gedinakova

- Update all import statements to use defineComponents().
- Changed the theme to bootstrap.

Closes #142

2021-11-09 07:55 UTC, DiyanDimitrov requested changes
Button and link-button are still using material theme and old imports. Also we have a `import 'igniteui-webcomponents'` in the `browser\src\index.ts` file which I think is no longer needed.

2021-11-09 08:11 UTC, simeonoff approved these changes

2021-11-10 09:42 UTC, igdmdimitrov commented on samples/inputs/radio/styling/src/index.css
> -igc-radio::part(base checked):focus-within igc-radio::part(control) {
Styles are missing.

2021-11-10 09:42 UTC, igdmdimitrov commented on samples/grids/list/overview/src/index.ts
> +defineComponents(IgcListComponent, IgcListHeaderComponent, IgcListItemComponent, IgcRadioComponent, IgcRadioGroupComponent);
Missing avatar and button components.

2021-11-10 09:42 UTC, igdmdimitrov commented on samples/menus/nav-drawer/add-positions-navbar/src/index.ts
> +defineComponents(IgcNavDrawerComponent, IgcNavDrawerHeaderItemComponent, IgcNavDrawerItemComponent,
Missing navbar component.

2021-11-10 11:42 UTC, onlyexeption commented on samples/layouts/card/horizontal/src/index.ts
> +import { defineComponents, IgcCardComponent, IgcCardHeaderComponent, IgcCardContentComponent, IgcCardMediaComponent, IgcCardActionsComponent} from 'igniteui-webcomponents';
IgcCardMedia is not used in the html of this sample

2021-11-10 13:20 UTC, DiyanDimitrov approved these changes

2021-11-10 14:28 UTC, simeonoff approved these changes

2021-11-10 14:28 UTC, merged