fix(dock-manager): add improvements for styling sample
IgniteUI/igniteui-wc-examples pull request #185
Opened 2021-11-22 08:07 UTC by zhosti

Closes #118

2021-11-23 15:02 UTC, DiyanDimitrov requested changes
We should dock and pin the floating pane when the user click pin on a floating pane.

2021-11-23 15:02 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/styling/src/index.ts
> +        registerIcon("arrow-up", "https://fonts.gstatic.com/s/i/materialiconsoutlined/arrow_drop_up/v12/24px.svg", "material");
Use registeIconFromText.

2021-11-23 15:11 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/styling/src/index.ts
> +        this.dockManager.layout = { ...this.layout };
We should use the actual reference of the layout. Same for `handlePinPane`.
```suggestion
        this.dockManager.layout = { ...this.dockManager.layout };
```

2021-11-23 15:37 UTC, HUSSAR-mtrela requested changes
please remove all these images and email them to me. I will add them to CDN from where we can share these images between SB on all platforms

2021-11-25 13:09 UTC, DiyanDimitrov approved these changes

2021-12-03 17:09 UTC, HUSSAR-mtrela requested changes
please resolve conflicts

2021-12-06 13:45 UTC, DiyanDimitrov approved these changes

2021-12-06 21:20 UTC, HUSSAR-mtrela approved these changes

2021-12-06 21:20 UTC, merged