Update clipboard operations sample.
IgniteUI/igniteui-wc-examples pull request #421
Opened 2023-04-24 11:43 UTC by MayaKirova

Update UI elements since the property editor ones do not work correctly.

2023-04-24 18:33 UTC, HUSSAR-mtrela requested changes

2023-04-24 18:33 UTC, HUSSAR-mtrela commented on samples/grids/grid/clipboard-operations/index.html
> +      <igc-button id="selectionClear">Clear selection</igc-button>
this sample is exported from xplat samples
https://github.com/IgniteUI/igniteui-xplat-examples/blob/vnext/samples/grids/grid/clipboard-operations.json
but I do not see a PR with your changes in igniteui-xplat-examples repo. Did you forget to create the PR or are you converting this xplat samples to platform specific sample?

2023-04-25 07:38 UTC, MayaKirova commented on samples/grids/grid/clipboard-operations/index.html
> +      <igc-button id="selectionClear">Clear selection</igc-button>
@HUSSAR-mtrela I disabled in this PR: https://github.com/IgniteUI/igniteui-xplat-examples/pull/199
With the intention of adding platform specific samples for WC and Blazor.

By the way, could you not merge PRs since @dkamburov would also like to review and test them before merging.

2023-05-16 13:09 UTC, mddragnev submitted a review, later dismissed

2023-07-06 17:28 UTC, HUSSAR-mtrela approved these changes

2023-09-29 08:27 UTC, mddragnev commented
@dkamburov and this as well can be merged. I will enable the topic

2023-09-29 08:30 UTC, mddragnev commented
@HUSSAR-mtrela Could you take a look at the failing build. Seems like all of the builds are failing not only in this PR

2023-10-03 18:25 UTC, merged