Add a keyboard navigation guide sample.
IgniteUI/igniteui-wc-examples pull request #449
Opened 2023-05-17 12:42 UTC by MayaKirova

Add a keyboard navigation guide sample.

2023-09-29 13:23 UTC, mddragnev commented
@dkamburov This is still not merged

2023-12-13 14:01 UTC, skrustev requested changes

2023-12-13 14:01 UTC, skrustev commented on samples/grids/grid/keyboard-navigation-guide/src/index.ts
> +        if (col.collapsible) {
Only this needs the col to be casted to `IgcColumnGroupComponent`, otherwise throws error.

2023-12-13 17:01 UTC, HUSSAR-mtrela approved these changes

2023-12-13 17:01 UTC, merged