Add panel hiding sample for Dock Manager
IgniteUI/igniteui-wc-examples pull request #49
Opened 2021-04-13 14:27 UTC by zhosti

![hide-panes](https://user-images.githubusercontent.com/7760119/114568229-a0a55680-9c7c-11eb-9b5a-2dca748f784e.png)

2021-04-14 15:02 UTC, gedinakova approved these changes

2021-04-16 13:07 UTC, DiyanDimitrov requested changes

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/ReadMe.md
> +This folder contains implementation of Web Components application with example of Dock Manager Hidding Panes.
```suggestion
This folder contains implementation of Web Components application with example of Dock Manager Hiding Panes.
```

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/DockManagerStyles.css
> +.dockManagerFull {
Do we need to have styles which are not used in this sample?

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +    private hideOnCloseCheckbox: HTMLInputElement;
Since the purpose of this sample is to show hiding instead of closing I think that having such checkbox is unnecessary. Let's always hide the panes.

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +    }
Remove obsolete code.

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +        this.dockManager.addEventListener("paneClose", (ev) => {
```suggestion
        this.dockManager.addEventListener("paneClose", (ev: CustomEvent<IgcPaneCloseEventArgs>) => {
```

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +    private savedLayout: string;
Remove obsolete member.

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +        this.showAllPanes();
It is a bit strange to have a `showPane` method which actually subscribes to a button click instead of showing the pane. I would suggest to refactor these methods like this:
```ts
document.getElementById("showPane")?.addEventListener("click", () => {
    this.showPane();
});
```

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +        option.value = pane.id!;
Do we need the value?

2021-04-16 13:07 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/index.html
> +      <select name="panes" id="panes" class="igOptions-input-text"></select>
Could we try to better align these two?

2021-04-16 15:02 UTC, zhosti commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +        option.value = pane.id!;
Actually no. I was using it for already deleted functionality.

2021-04-16 15:05 UTC, zhosti commented on samples/layouts/dock-manager/hiding-panes/src/DockManagerStyles.css
> +.dockManagerFull {
No. I'll remove them.

2021-04-19 13:01 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +        this.showAllPanes();
Please do the same for the other two methods - `handlePaneClose` and `showAllPanes`.

2021-04-19 13:53 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +import { IgcDockManagerComponent } from "igniteui-dockmanager";
Combine the imports from the "igniteui-dockmanager" module.

2021-04-19 14:28 UTC, DiyanDimitrov commented on samples/layouts/dock-manager/hiding-panes/src/index.ts
> +    public handlePaneClose() {
```suggestion
    private handlePaneClose() {
```

2021-04-19 16:30 UTC, DiyanDimitrov approved these changes

2021-04-20 14:11 UTC, gedinakova approved these changes

2021-04-20 14:48 UTC, DiyanDimitrov commented
@HUSSAR-mtrela the PR is ready for merging. Could you please review it and merge it if it is ok?

2021-04-23 21:50 UTC, HUSSAR-mtrela approved these changes

2021-04-23 21:51 UTC, merged