Update custom samples with updated NwinData class.
IgniteUI/igniteui-wc-examples pull request #621
Opened 2023-12-14 13:32 UTC by skrustev

2024-01-09 08:04 UTC, tishko0 submitted a review, later dismissed

2024-01-23 21:55 UTC, HUSSAR-mtrela requested changes
@skrustev what's the reason for changing this data source? 
Also, you should be making changes to NwindData in xplat repo because NwindData is auto-generated from there:
https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/code-gen-library/NwindData/XPLAT.json

2024-04-10 11:03 UTC, dkamburov commented
@skrustev can you please take a look at the comment from Martin

2024-11-15 08:58 UTC, kdinev commented
@dkamburov Reminder about this PR still being open.

2024-11-15 13:15 UTC, skrustev commented
This back when the data generation was altered. This is for the custom samples.

2025-05-15 16:03 UTC, closed without merging